name: Generating Result

on:
  workflow_dispatch:
    inputs:
      Homework:
        description: 'The number of homework you would like to test'
        required: true

jobs:
  manipulate_files:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: "Check file existence"
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "result/diffs_hw${{ github.event.inputs.Homework }}.txt"
    
    - name: Delete old diff.txt file
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git rm result/diffs_hw${{ github.event.inputs.Homework }}.txt
        git commit -m "remove old file"
        git push
        
    - name: Write to file
      run: |
        echo "### run docker ###"
        docker run --rm --name pocsd --mount type=bind,source="$(pwd)",target=/tmp rjofig/pocsdgrading ${{ github.event.inputs.Homework }}
        echo "### write the result ###"
        mkdir -p result
        mv *.txt result/
        
    - name: Commit changes
      run: |
        echo "### git config ###"
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo "### git add ###"
        git add .
        echo "### git commit ###"
        git commit -m "generated"
        echo "### git push ###" 
        git push
